### ISSUE TITLE
scons issue

### ISSUE THREAD

**Issue by 00000000002** [evilbinary/YiYiYa#21]
when i exceute 编译与运行
#清理
scons -c
#编译
scons -j8
#运行
scons --run=qscons ,error happen...
![35Q$@P5S(A~4S5PMQZ6A@`D](https://user-images.githubusercontent.com/52356585/235714532-43071b58-8a82-4f04-9cea-3fd07cc1d2fb.png)

#

**Comment by 00000000002** [comment]
Please write detailed compilation and running documents that seem too complicated to understand, such as the section on the Socon。。3Q

**Comment by evilbinary** [comment]
please config build target first, the default config is for esp32 platform,you could do this config follow the document first at https://github.com/evilbinary/YiYiYa/blob/main/docs/develop/%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83.md

<img width="895" alt="image" src="https://user-images.githubusercontent.com/5143386/235717820-a92e2e89-685c-4356-ac10-8b73b7c0ae57.png">



<img width="552" alt="image" src="https://user-images.githubusercontent.com/5143386/235717479-37ce6aed-3337-4b35-9e6a-a46f86190a88.png">

**Comment by 00000000002** [comment]
The operating system is Ubantu 14.04, so which parameter should I choose for configuration

**Comment by evilbinary** [comment]
please read the document first ,this document will teach you how to config.
